### ISSUE TITLE
Broken search when special characters in search query: #, +

### ISSUE THREAD

**Issue by 4www** [internet4000/find#1]
This search `test #3232323` does not take in consideration all the part from the `#` and on.

Example searches:

- `1 + 2` : this should just default to duck duck go and it would say that it equals `3`, but right now the `+` sign is stripped out from the search query

**Comment by 4www** [comment]
is this related to https://github.com/internet4000/radio4000/issues/222 ?

**Comment by oskarrough** [comment]
shouldn't the query be encoded before sending it do duckduckgo etc?

encodeURIComponent('test #123')

**Comment by 4www** [comment]
I don't think It should be encoded because when the engines receive the string as a request they won't decode it. Or will they?

**Comment by oskarrough** [comment]
If you send a non-encoded query like `https://duckduckgo.com/?q=not encoded` it will redirect to the encoded variant: https://duckduckgo.com/?q=not%20encoded. Same for google.

So it looks to be safe to encode it? But I only tested by entering URL into the browser address bar.

**Comment by 4www** [comment]
Maybe two things need to be sanitized
`userRequest` https://github.com/internet4000/find/blob/master/main.js#L76
`requestTerms` https://github.com/internet4000/find/blob/master/main.js#L83

**Comment by hellerve** [comment]
Yup, it definitely needs to be URL-encoded.
