### ISSUE TITLE
!c action not working

### ISSUE THREAD

**Issue by oskarrough** [internet4000/find#10]
When I do `!c oskar` I end up at

- https://www.google.com/contacts/u/0/?cplus=0

but I expect to land on this?

- https://www.google.com/contacts/u/0/?cplus=0#contacts/search/oskar

Is it contacts.google.com or google.com/contacts? And the `/u/0` part is because I'm signed in with multiple google accounts.

https://github.com/internet4000/find/blob/28266927633a7a11901e9440cc2e2423af75be61/main.js#L10

**Comment by 4www** [comment]
Hum, interesting issue.

I use https://contacts.google.com, the link you use show me a different application.

Does this link works for you?

It seems you are using the old google interface. You can upgrade to the new one by clicking the last link in the aside left nav menu, and then I guess it should work fine.

More generally, we might get into this isssue again with other sites.

**Comment by oskarrough** [comment]
I think it is because I'm using a Google Apps account and not a regular gmail. So I can't upgrade to the new interface yet.. For my gmail the other URL does work.

**Comment by 4www** [comment]
You can upgrade but you have to upgrade it for your organization in its entirety
