### ISSUE TITLE
+ and # symbol seems not to work properly from Firefox URL bar

### ISSUE THREAD

**Issue by 4www** [internet4000/find#50]
can't call any of the `+` symbol engines.
`+r4 <youtube-url>` or `+r4p <radio-slug>` should work, but they do not.

To investigate

**Comment by oskarrough** [comment]
It works on https://find.internet4000.com for me.

**Comment by 4www** [comment]
yes true, but not from the URL bar, weirdly.

Actually it does not work in Firefox but it does in chrome.

Maybe it is a firefox update thatdoes something to the first character if it is a `+`?

Haventinvestigated yet D:

**Comment by oskarrough** [comment]
Hm true, doesn't work in my Firefox's URL bar. Version 66.

**Comment by oskarrough** [comment]
maybe here https://bugzilla.mozilla.org/buglist.cgi?resolution=---&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&query_format=advanced&component=Address%20Bar

**Comment by 4www** [comment]
<img width="687" alt="firefox" src="https://user-images.githubusercontent.com/1502484/54985548-465fcd00-4fb1-11e9-821e-cf42106bfcdb.png">

**Comment by 4www** [comment]
It seems that in firefox, you can user `++`, so the second + is not swallowed by Firefox.

Idon't think moving all engines under one symbol is an alternative. I think symbols gives a useful meaning to what the engines under do.

For now using `++` on Firefox is satisfying for me

**Comment by hellerve** [comment]
Both `+` and `#` work for me on Firefox in OS X in the URL bar now.

**Comment by 4www** [comment]
seems to be working good (now -_-)
