### ISSUE TITLE
https only check

### ISSUE THREAD

**Issue by 4www** [internet4000/find#52]
Make a check in the script that prevents it to run on non https connections.

It is one check more for every request, but it seems important to prevent anyone to use it on non https connections.

Does this make sense? @hellerve ?

**Comment by hellerve** [comment]
Makes sense; I think the user’s queries should be private at all times!

**Comment by 4www** [comment]
this is currently left to the symbol/engine's definition.

Also since the browser first catches a URL, find is left with a "user query" to interpret, which it usually does not transform, and only use to fill placeholders in the destination URL.

Closing since that seems handled/fixed.

> Note: a user should not register a `http://` site, and if they do, the browsers should now warn them before entering
