### ISSUE TITLE
netlify deploys branch `production`, maybe `master` instead?

### ISSUE THREAD

**Issue by 4www** [internet4000/find#62]
netlify deploys branch `production`

maybe it could be the branch `master` instead?

This would remove some overhead of publish to live version,
but add the possibility of bugs introduced on master

**Comment by oskarrough** [comment]
Depends on the project for sure, but here it seems fine to deploy master directly. No need for a second branch in my opinion.

Could rename to `main` now we're at it ;) https://github.com/internet4000/find/branches

**Comment by 4www** [comment]
now deploys on github pages with actions (should work on more CI/CD and providers -netlify,vercel,etc.- recipes)
