### ISSUE TITLE
Firefox changes default search url from self-host instance of i4k to the find.internet4000.com site

### ISSUE THREAD

**Issue by 97997** [internet4000/find#73]
I host my own i4k instance and when i add it to firefox as the default search engine it works correctly for some time, but eventually always changes from my own instance to the https://find.internet4000.com/ website and to fix it i need to delete the search engine from firefox and re-add it, but is just a matter of time until it changes again to https://find.internet4000.com/ 
funnily enough firefox for android doesnt seem to have this issue, is there any way to avoid this bug?

**Comment by 4www** [comment]
Hello, thanks for opening an issue. I've never encountered this, to debug, could you check:
- which version of find are you using? You can find this information in the `package.json` file https://github.com/internet4000/find/blob/master/package.json#L3 of the "find source code" you use
- if all "custom instance" steps were correctly followed https://github.com/internet4000/find#host-your-own-instance
- if there are any reference to `find.internet4000.com` in the code you use https://github.com/internet4000/find/search?q=find.internet4000.com
- when this bug happens, does `find.internet4000.com` becomes referenced into your browser's search engines?
- can you share the link to your instance to debug the code? Or to the repository of the code you use to deploy?

Let me know if I can further assist

**Comment by 4www** [comment]
Hi! Could you find a solution this issue?

There has been updates, and the generation of the XML should be easier now.

For reference:
- the script to run https://github.com/internet4000/find/blob/main/src/scripts/opensearch-xml.js
- the "end genreated example file" https://github.com/internet4000/find/blob/main/assets/opensearch.xml
- the xml generated by the script, checked in the tests https://github.com/internet4000/find/blob/main/src/tests/open-search.js#L14-L24

Feel free to re-open if there is still an issue!
